import { createCrudController } from './crudController.js';
import { Patient } from '../models/Patient.js';
import { Doctor } from '../models/Doctor.js';
import { Appointment } from '../models/Appointment.js';
import { Prescription } from '../models/Prescription.js';
import { MedicalRecord } from '../models/MedicalRecord.js';
import { LabReport } from '../models/LabReport.js';
import { Medicine } from '../models/Medicine.js';
import { Inventory } from '../models/Inventory.js';
import { Room } from '../models/Room.js';
import { Bed } from '../models/Bed.js';
import { Admission } from '../models/Admission.js';
import { Bill } from '../models/Bill.js';
import { Payment } from '../models/Payment.js';
import { User } from '../models/User.js';

export const patients = createCrudController(Patient);
export const doctors = createCrudController(Doctor, ['userId']);
export const appointments = createCrudController(Appointment, ['patientId', 'doctorId']);
export const prescriptions = createCrudController(Prescription, ['patientId', 'doctorId']);
export const medicalRecords = createCrudController(MedicalRecord, ['patientId', 'doctorId', 'prescriptions']);
export const labReports = createCrudController(LabReport, ['patientId', 'doctorId']);
export const medicines = createCrudController(Medicine);
export const inventory = createCrudController(Inventory, ['medicineId']);
export const rooms = createCrudController(Room);
export const beds = createCrudController(Bed, ['roomId', 'currentPatientId']);
export const admissions = createCrudController(Admission, ['patientId', 'doctorId', 'roomId', 'bedId']);
export const bills = createCrudController(Bill, ['patientId']);
export const payments = createCrudController(Payment, ['billId', 'patientId']);
export const users = createCrudController(User);
